server:
  port: 5006

spring:
  application:
    name: eureka-server

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:5006/eureka/

  server:
    enable-self-preservation: true

  instance:
    hostname: localhost